### ISSUE TITLE
Jobstate enum

### ISSUE THREAD

**Issue by tonirv3** [deesejohn/Reinforce#100]
Hi, seems that the state InProgress misses in jobstate enum.

Sometimes, we get an exception wheten call  get job info method.

Thanks

**Comment by deesejohn** [comment]
@tonirv3, that state isn't documented for that enum: https://developer.salesforce.com/docs/atlas.en-us.api_bulk_v2.meta/api_bulk_v2/get_job_info.htm

Can you attach a stack trace and/or screenshot?

**Comment by deesejohn** [comment]
It looks like another project is using that enum value, so I've opened a PR: https://github.com/deesejohn/Reinforce/pull/102

**Comment by deesejohn** [comment]
v 1.0.3 should resolve this issue
