### ISSUE TITLE
How do we query the next result from a query ?

### ISSUE THREAD

**Issue by Davilink** [deesejohn/Reinforce#105]
With the result below, how can a retrieve the next batch of record ?
```json
{
"done": false,
"nextRecordsUrl": "/services/data/v47.0/query/01g3n00008GMxpxAAD-2000",
...
}
```

normally we would use the "nextRecordsUrl", but the api doesn't seem to have anything to use that.

**Comment by deesejohn** [comment]
I should have answered your question instead of just closing the issue, but you can now `GetNextByUrlAsync` on `IQuery` in v1.0.5+

**Comment by Davilink** [comment]
No problem. I should have told you that it work great. Thx for the quick fix
