### ISSUE TITLE
Bug on IServiceCollectionExtensions.cs

### ISSUE THREAD

**Issue by tonirv3** [deesejohn/Reinforce#97]
Hi, when we use the service collection extensions on startup.cs, we get this error  :

System.InvalidOperationException: 'The HttpClient factory already has a registered client with the name 'IReinforceBuilder', bound to the type 'Reinforce.ApexRest.IApexRest'. Client names are computed based on the type name without considering the namespace ('IApexRest'). Use an overload of AddHttpClient that accepts a string and provide a unique name to resolve the conflict.'

This error also happens when i try to run your AccountApi.

Thanks in advance

**Comment by tonirv3** [comment]
It's a bug on net core from 3.0.0, with net.core 2.2 works!

**Comment by deesejohn** [comment]
Looks like an issue with HttpClientFactory itself: https://github.com/aspnet/AspNetCore/issues/13346

I'll see if there is an easy work around.

**Comment by deesejohn** [comment]
I updated the library use `Microsoft.Extensions.Http` which targets dotnet core 3.1 and the bug with HttpClientFactory appears to be resolved. I have a PR open here: https://github.com/deesejohn/Reinforce/pull/98

**Comment by deesejohn** [comment]
0.9.2 is released

**Comment by tonirv3** [comment]
Hi, 
seems that this errour continue failing, when I launch your AccountApi, I get the next error again : 

_System.InvalidOperationException: 'The HttpClient factory already has a registered client with the name 'IReinforceBuilder', bound to the type 'Reinforce.ApexRest.IApexRest'. Client names are computed based on the type name without considering the namespace ('IApexRest'). Use an overload of AddHttpClient that accepts a string and provide a unique name to resolve the conflict.'_


I attached you an image : 

![image](https://user-images.githubusercontent.com/16175071/73933196-33f63580-48dc-11ea-9120-73186629fba7.png)

Thanks in advance

**Comment by deesejohn** [comment]
It looks like they pushed a fix: https://github.com/dotnet/extensions/commit/f198c4653a310e4d9957cc37a22a649ef020e69e

I'm updating MS Extension deps to 3.1.1

**Comment by deesejohn** [comment]
v 1.0.2 should hopefully resolve the issue. Please let me know if this is not the case.

**Comment by tonirv3** [comment]
I'm sorry to inform you that i still get the same crash, i get this error when call the second time to the method : 
private static IHttpClientBuilder AddRestClient<TApi>(this IHttpClientBuilder builder)
on your Iservicecollectionextension.cs class.

![image](https://user-images.githubusercontent.com/16175071/74022353-9f540c00-499d-11ea-8509-9fd9bd2079fa.png)

I am launching your AccountApi at reinforce solution.

**Comment by deesejohn** [comment]
@tonirv3, I ended up having time to dig into this and was able to recreate the error locally. I noticed MS Extensions have the bugfix in their master branch but haven't released it via nuget yet. I created a work around in PR #103 that was able to resolve the issue for me locally.

**Comment by deesejohn** [comment]
v 1.0.4 released
